---
- name: Install docker runtime packages (p0 + picluster + management)
  ansible.builtin.apt:
    name: "{{ docker_runtime_packages }}"
    state: present
    update_cache: true
  when: docker_runtime_enable and (('master' in group_names) or ('picluster' in group_names) or ('management' in group_names))

- name: Install docker runtime packages on zeros (optional)
  ansible.builtin.apt:
    name: "{{ docker_runtime_packages }}"
    state: present
  when: docker_runtime_enable and docker_runtime_on_zeros and 'zerocluster' in group_names

- name: Ensure docker service enabled
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  when: >-
    docker_runtime_enable and (
      ('master' in group_names) or
      ('picluster' in group_names) or
      ('management' in group_names) or
      (docker_runtime_on_zeros and 'zerocluster' in group_names)
    )
