---
- name: Check unpartitioned space
  shell: /sbin/parted /dev/mmcblk0 unit gb print free | grep 'Free Space' | tail -n1 | awk '{print $3}'
  become: yes
  register: unpartitioned
  changed_when: false
  failed_when: unpartitioned.stderr != ""

- name: Expand filesystem to fill disk
  command: raspi-config --expand-rootfs
  become: yes
  when: unpartitioned.stdout != "0.00GB"

- name: Reboot after file system change
  reboot:
  become: yes
  when: unpartitioned.stdout != "0.00GB"

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
