---
- name: Install packages
  apt:
    name: "{{ packages }}"
    update_cache: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
