---
- name: Hostname | Set system hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ hostname_fqdn_full }}"

- name: Hostname | Render consolidated /etc/hosts
  become: true
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ hostname_hosts_file_location }}"
    owner: root
    group: root
    mode: "0644"
    backup: "{{ hostname_hosts_backup | bool }}"
  vars:
    hostname_all_groups_order: [ 'master','zerocluster','picluster','management' ]
  tags: ['hosts']

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
