---
- name: Set up SSH on ZeroCluster
  hosts: zerocluster
  vars:
    - ansible_connection: ssh
    - ansible_user: pi
    - ansible_ssh_pass: zerocluster
  roles:
    - role: hostname
  tasks:
  - name: Create .ssh folder
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: Create authorized_keys file
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: ~/.ssh/authorized_keys
      owner: pi
      group: pi
      mode: 0600

- name: Set up SSH on PiCluster
  hosts: picluster
  vars:
    - ansible_connection: ssh
    - ansible_user: pi
    - ansible_ssh_pass: raspberry
  roles:
    - role: hostname
  tasks:
  - name: Create .ssh folder
    file:
      path: ~/.ssh
      state: directory
      mode: 0700

  - name: Create authorized_keys file
    copy:
      src: ~/.ssh/id_rsa.pub
      dest: ~/.ssh/authorized_keys
      owner: pi
      group: pi
      mode: 0600

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
