---
- name: Clusterhat set-up
  hosts: master
  become: true
  collections:
    - community.crypto
  vars_files:
    - vars/vars.yml
  roles:
    - role: hostname
    - role: installpkg
      installpkg_packages: "{{ apt_pkg }}"
  tasks:
    - name: Configure master OS
      ansible.builtin.include_tasks: tasks/master.yml
      when: "'master' in group_names"

    - name: Set up ssh
      ansible.builtin.include_tasks: tasks/ssh.yml

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
