---
- name: Clusterhat set-up
  hosts: master
  become: yes
  vars_files:
    - vars/vars.yml
  roles:
    - role: hostname
    - role: installpkg
      packages: "{{ apt_pkg }}"
  tasks:
    - name: Fix root permissions
      include_tasks: tasks/fixroot.yml

    - name: Configure master OS
      include_tasks: tasks/master.yml
      when: "'master' in group_names"

    - name: Set up ssh
      include_tasks: tasks/ssh.yml

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
