---
collections:
  - name: community.crypto
    version: "2.13.1"
  - name: community.general
    version: "8.5.0"
  - name: ansible.utils
    version: "2.12.0"
  - name: ansible.posix
    version: "1.5.4"
