---
collections:
  - name: community.crypto
    version: ">=2.0.0"
  - name: community.general
    version: ">=8.0.0"
  - name: ansible.utils
    version: ">=2.12.0"
  - name: ansible.posix
    version: ">=1.5.0"
