---
- name: Clusterhat set-up
  hosts: zerocluster
  gather_facts: no
  become: yes
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Wait until all nodes are started
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        search_regex: OpenSSH
        delay: 10
      connection: local

    - name: Set up boot from sdcard
      include_tasks: tasks/sdcboot.yml

    - name: Restarting the cluster
      reboot:

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
