---
- name: ClusterHAT usbboot provisioning
  hosts: clusterhat
  become: true
  gather_facts: true
  vars_files:
    - vars/usbboot.yml
  tasks:
    - name: Get Cluster Status
      ansible.builtin.command: "{{ clusterctrl_bin }} status"
      register: cluster_status
      changed_when: false
      tags: ['usbboot','power','status']

    - name: Set cluster_power_status fact (reuse status output)
      ansible.builtin.set_fact:
        cluster_power_status: "{{ cluster_status }}"
      tags: ['usbboot','power']

    - name: Power off all zeros
      ansible.builtin.command: "{{ clusterctrl_bin }} off"
      become: true
      changed_when: false
      failed_when: false
      run_once: true
      tags: ['usbboot','power']

    - name: Refresh cluster status after power off
      ansible.builtin.command: "{{ clusterctrl_bin }} status"
      register: cluster_status_after_off
      changed_when: false
      tags: ['usbboot','power','status']

    - name: Update cluster_power_status with refreshed output
      ansible.builtin.set_fact:
        cluster_power_status: "{{ cluster_status_after_off }}"
      tags: ['usbboot','power','status']

    - name: Set up usbboot provisioning filesystem contents
      ansible.builtin.include_tasks:
        file: tasks/usbboot.yml
        apply:
          tags:
            - usbboot
            - provision
      tags: ['usbboot','provision']

    - name: Configure DNS for zeros (resolv.conf)
      ansible.builtin.copy:
        dest: "/var/lib/clusterctrl/nfs/p{{ zero_node | regex_search('[0-9]+') }}/etc/resolv.conf"
        content: |-
          search tripnet.be
          nameserver 172.16.2.51
          nameserver 1.1.1.1

        owner: root
        group: root
        mode: '0644'
        force: true
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      become: true
      tags: ['usbboot','dns']

    - name: Configure DNS for controller (resolv.conf)
      ansible.builtin.copy:
        dest: "/etc/resolv.conf"
        content: |-
          search tripnet.be
          nameserver 172.16.2.51
          nameserver 1.1.1.1

        owner: root
        group: root
        mode: '0644'
        force: true
      become: true
      tags: ['usbboot','dns']

    - name: Set hostname in zero rootfs (/etc/hostname)
      ansible.builtin.copy:
        dest: "/var/lib/clusterctrl/nfs/p{{ zero_node | regex_search('[0-9]+') }}/etc/hostname"
        content: "z{{ zero_node | regex_search('[0-9]+') }}\n"
        owner: root
        group: root
        mode: '0644'
        force: true
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      become: true
      tags: ['usbboot','provision','hostname']

    - name: Render /etc/hosts in zero rootfs
      ansible.builtin.template:
        src: roles/hostname/templates/hosts.j2
        dest: "/var/lib/clusterctrl/nfs/p{{ zero_node | regex_search('[0-9]+') }}/etc/hosts"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      vars:
        hostname_all_groups_order: [ 'master','zerocluster','picluster','management' ]
        hostname_fqdn_short: "z{{ zero_node | regex_search('[0-9]+') }}"
      become: true
      tags: ['usbboot','provision','hosts']

    - name: Ensure ClusterCTRL block is commented in dhclient.conf for each zero
      ansible.builtin.include_tasks:
        file: tasks/comment_dhclient.yml
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      vars:
        zero_node: "{{ zero_node }}"
      tags: ['usbboot','provision','network']

    - name: Power on nodes
      ansible.builtin.command:
        argv: ["{{ clusterctrl_bin }}", "on", "p{{ zero_node | regex_search('[0-9]+') }}"]
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      become: true
      when: power_on | default(true) | bool and
            ("p" + (zero_node | regex_search('[0-9]+')) + ":0") in cluster_power_status.stdout
      tags: ['usbboot','power']

    - name: Build list of zero IPs
      ansible.builtin.set_fact:
        zero_ips: >-
          {{ groups['zerocluster'] | map('extract', hostvars, 'ipaddr') | select('defined') | list }}
      run_once: true
      tags: ['usbboot','wait','ssh']

    - name: Wait for SSH on all zeros using until loop
      ansible.builtin.wait_for:
        host: "{{ item }}"
        port: 22
        timeout: 5
        state: started
      loop: "{{ zero_ips }}"
      register: ssh_probe
      until: ssh_probe is not failed
      retries: 60
      delay: 10
      when: (zero_ips | length) > 0
      tags: ['usbboot','wait','ssh']

    - name: Pause to allow zeros to finish booting
      ansible.builtin.pause:
        seconds: 60
      tags: ['usbboot','wait']

    - name: Create SSH directory in user home
      ansible.builtin.file:
        path: "/var/lib/clusterctrl/nfs/p{{ zero_node | regex_search('[0-9]+') }}/home/{{ pi_user | default('pi') }}/.ssh"
        state: directory
        mode: '0700'
        owner: 1000
        group: 1000
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      become: true
      tags: ['usbboot','provision','ssh','keys']

    - name: Create authorized_keys in user home
      ansible.builtin.copy:
        dest: "/var/lib/clusterctrl/nfs/p{{ zero_node | regex_search('[0-9]+') }}/home/{{ pi_user | default('pi') }}/.ssh/authorized_keys"
        content: "{{ cluster_public_ssh_key }}\n"
        mode: '0600'
        owner: 1000
        group: 1000
      loop: "{{ groups['zerocluster'] }}"
      loop_control:
        loop_var: zero_node
      become: true
      when: cluster_public_ssh_key is defined
      tags: ['usbboot','provision','ssh','keys']

    - name: Install SSH keys from files/ssh onto clusterhat
      ansible.builtin.copy:
        src: "{{ item.0 }}"
        dest: "/var/lib/clusterctrl/nfs/p{{ item.1 | regex_search('[0-9]+') }}/home/{{ pi_user | default('pi') }}/.ssh/{{ item.0 | basename }}"
        owner: 1000
        group: 1000
        mode: "{{ '0644' if (item.0 | regex_search('\\.pub$')) else '0600' }}"
        force: true
      loop: "{{ query('fileglob', 'files/ssh/*') | product(groups['zerocluster']) | list }}"
      loop_control:
        label: "{{ (item.0 | basename) ~ ' -> ' ~ item.1 }}"
      become: true
      tags: ['usbboot','ssh','keys']
      
    - name: Final status
      ansible.builtin.command:
        argv: ["{{ clusterctrl_bin }}", "status"]
      register: final_status
      changed_when: false
      become: true
      run_once: true
      tags: ['usbboot','status']

    - name: Summarize provisioning results
      ansible.builtin.debug:
        msg: >-
          Archive={{ usbboot_local_archive_path }} present={{ usbboot_archive_stat.stat.exists | default('n/a') }};
          Extracted nodes={{ groups['zerocluster'] | join(',') }}; Power managed={{ power_on | default(true) }}.
      run_once: true
      tags: ['usbboot','summary']

    - name: Show final status
      ansible.builtin.debug:
        var: final_status.stdout
      run_once: true
      tags: ['usbboot','status']

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
