---
- name: Cluster set-up
  hosts: master:zerocluster
  become: yes
  vars_files:
    - vars/vars.yml
    - vars/cluster.yml
  roles:
    - role: hostname
    - role: installpkg
      packages: "{{ apt_pkg }}"
  tasks:
    - name: Fix root permissions
      include_tasks: tasks/fixroot.yml

    - name: Configure master OS
      include_tasks: tasks/master.yml
      when: "'master' in group_names"

    - name: Add static route for picluster to zerocluster
      copy:
        src: files/picluster/40-route
        dest: /lib/dhcpcd/dhcpcd-hooks/40-route
        owner: root
        group: root
        mode: 0644
      when: "'picluster' in group_names"

    - name: Apply the route
      command: ip ro add 172.19.180.0/23 via 172.16.2.200 dev eth0
      when: "'picluster' in group_names"
      ignore_errors: true

    - name: Mount master share
      mount:
        path: /opt/data
        src: 172.19.180.254:/opt/data
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs
      when: "'master' not in group_names"

    - name: Create alias file
      become_user: pi
      file:
        path: ~/.bash_aliases
        state: touch

    - name: Set up aliases
      become_user: pi
      lineinfile:
        path: ~/.bash_aliases
        line: "{{ item }}"
        state: present 
      with_items:
        - 'alias ll="exa -Slhg --icons"'
        - 'alias la="exa -Slhga --icons"'
        - 'alias lt="exa -T --icons"'

    - name: Set up ssh
      include_tasks: tasks/ssh.yml

    - name: Configure munge
      include_tasks: tasks/munge.yml
      when: munge

    - name: Configure slurm
      include_tasks: tasks/slurm.yml
      when: slurm

# vim: set ft=yaml.ansible ts=4 sw=2 tw=80 et :
