---
- name: Fix root tree ownership
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
  with_items:
    - /
    - /etc
    - /sbin
    - /usr
  become: true
