---
- name: Populate /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item.hostname }}$"
    line: "{{ item.address }} {{ item.hostname }}"
    state: present
  with_items:
    - { hostname: controller, address: 172.19.181.254 }
    - { hostname: z1, address: 172.19.181.1 }
    - { hostname: z2, address: 172.19.181.2 }
    - { hostname: z3, address: 172.19.181.3 }
    - { hostname: z4, address: 172.19.181.4 }
    - { hostname: clusterhat, address: 172.16.2.200 }
    - { hostname: p1, address: 172.16.2.201 }
    - { hostname: p2, address: 172.16.2.202 }
    - { hostname: p3, address: 172.16.2.203 }
    - { hostname: p4, address: 172.16.2.204 }

- name: "Create mountpoints"
  ansible.builtin.file:
    path: "{{ clhat_mpnt }}"
    state: directory
    owner: root
    group: pi
    mode: 2775

- name: "Export /opt/data"
  ansible.builtin.lineinfile:
    dest: /etc/exports
    regexp: "^{{ item | regex_replace('(\\S+)\\s+.*', '\\1') }}\\s+.*$"
    line: "{{ item }}"
    state: present
  with_items:
    - "/opt/data  *(rw,fsid=1,no_root_squash,no_subtree_check,insecure)"

- name: "Reload nfsd"
  ansible.builtin.systemd:
    daemon_reload: true
    state: started
    name: nfs-kernel-server.service

- name: "Export shares"
  ansible.builtin.command: exportfs -rav
