---
- name: Install munge
  apt:
    name: "{{ munge_pkg }}"

- name: Copy munge key to nodes
  copy:
    src: files/munge/munge.key
    dest: /etc/munge/munge.key
    owner: munge
    group: munge
    mode: 0600

- name: Enable and restart munge
  systemd:
    name: munge
    state: restarted
    enabled: yes
