---
- name: Create mountpoints
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /mnt/root
    - /mnt/boot
    - /opt/data

- name: Mount master share
  mount:
    path: /opt/data
    src: 172.19.180.254:/opt/data
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs

- name: dd clusterhat image to /dev/mmcblk0
  command: "dd if={{ node_img }} of=/dev/mmcblk0 bs=2M"

- name: Mount sdcard filesystems
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: present
  with_items:
    - { path: "/mnt/boot", src: "/dev/mmcblk0p1", fstype: "vfat" }
    - { path: "/mnt/root", src: "/dev/mmcblk0p2", fstype: "ext4" }

- name: Create .ssh folder
  file:
    path: /mnt/root/home/pi/.ssh
    state: directory
    mode: 0700

- name: Create authorized_keys file
  copy:
    src: /home/pi/.ssh/id_rsa.pub
    dest: /mnt/root/home/pi/.ssh/authorized_keys
    owner: pi
    group: pi
    mode: 0600

- name: Unmount sdcard
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: absent
  with_items:
    - { path: "/mnt/boot", src: "/dev/mmcblk0p1", fstype: "vfat" }
    - { path: "/mnt/root", src: "/dev/mmcblk0p2", fstype: "ext4" }
