---
- name: Create mountpoints
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /mnt/root
    - /mnt/boot
    - /opt/data

- name: Mount master share
  ansible.builtin.mount:
    path: /opt/data
    src: 172.19.180.254:/opt/data
    opts: rw,sync,hard,intr
    state: mounted
    fstype: nfs

- name: Check existing image SHA (optional)
  ansible.builtin.command: "sha256sum {{ node_img }}"
  register: node_img_sum
  changed_when: false
  failed_when: false
  when: node_img is defined

- name: Write clusterhat image to /dev/mmcblk0 (skip if marker exists)
  ansible.builtin.command: "dd if={{ node_img }} of=/dev/mmcblk0 bs=2M status=progress"
  when: node_img is defined and (not sd_image_written.stat.exists)
  notify: Sync disks

- name: Create write marker
  ansible.builtin.file:
    path: /var/local/.clusterhat_sd_written
    state: touch
  when: node_img is defined and (not sd_image_written.stat.exists)

- name: Stat write marker
  ansible.builtin.stat:
    path: /var/local/.clusterhat_sd_written
  register: sd_image_written

- name: Mount sdcard filesystems
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: mounted
  loop:
    - { path: "/mnt/boot", src: "/dev/mmcblk0p1", fstype: "vfat" }
    - { path: "/mnt/root", src: "/dev/mmcblk0p2", fstype: "ext4" }

- name: Create .ssh folder
  ansible.builtin.file:
    path: /mnt/root/home/pi/.ssh
    state: directory
    mode: 0700

- name: Create authorized_keys file
  ansible.builtin.copy:
    src: /home/pi/.ssh/id_rsa.pub
    dest: /mnt/root/home/pi/.ssh/authorized_keys
    owner: pi
    group: pi
    mode: 0600

- name: Unmount sdcard
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    state: absent
  loop:
    - { path: "/mnt/boot", src: "/dev/mmcblk0p1", fstype: "vfat" }
    - { path: "/mnt/root", src: "/dev/mmcblk0p2", fstype: "ext4" }
