---
- name: Install slurm packages
  ansible.builtin.apt:
    name: "{{ slurm_pkg }}"
    state: present
    update_cache: yes

- name: Copy slurm config files
  ansible.builtin.copy:
    src: "files/slurm/{{ item }}"
    dest: "/etc/slurm/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ slurm_config_files }}"
  notify:
    - Restart slurmd
    - Restart slurmctld

- name: Ensure slurmd enabled & running
  ansible.builtin.systemd:
    name: slurmd
    enabled: true
    state: started

- name: Ensure slurmctld enabled & running (master only)
  ansible.builtin.systemd:
    name: slurmctld
    enabled: true
    state: started
  when: "'master' in group_names"
