---
- name: generate SSH key
  openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa
    size: 4096
    state: present
    force: no
  become: no

- name: Create ssh config file
  template:
    src: templates/ssh_config.j2
    dest: ~/.ssh/config
  become: no

