---
- name: Generate SSH key
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa
    size: 4096
    state: present
    force: false
  become: false

- name: Create ssh config file
  ansible.builtin.template:
    src: templates/ssh_config.j2
    dest: ~/.ssh/config
    mode: '0600'
  become: false
