---
- name: Restart munge
  ansible.builtin.service:
    name: munge
    state: restarted

- name: Restart slurmd
  ansible.builtin.service:
    name: slurmd
    state: restarted

- name: Restart slurmctld
  ansible.builtin.service:
    name: slurmctld
    state: restarted
