---
# Ensure custom bridge IP and default route with higher metric persist on clusterhat
- name: Ensure systemd unit for extra network config
  ansible.builtin.copy:
    dest: /etc/systemd/system/clusterhat-extra-net.service
    mode: '0644'
    content: |
      [Unit]
      Description=ClusterHAT extra network addresses
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/usr/local/sbin/clusterhat-extra-net.sh
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target

- name: Install helper script
  ansible.builtin.copy:
    dest: /usr/local/sbin/clusterhat-extra-net.sh
    mode: '0755'
    content: |
      #!/bin/bash
      set -euo pipefail
      ip addr show dev br0 | grep -q '172.16.2.200/' || ip addr add 172.16.2.200/24 brd + dev br0 metric 100
      ip route show default | grep -q 'via 172.16.2.1' || ip route add default via 172.16.2.1 dev br0 src 172.16.2.200 metric 100

- name: Enable and start service
  ansible.builtin.systemd:
    name: clusterhat-extra-net.service
    enabled: yes
    state: started
